apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ecommerce
  namespace: ecommerce
spec:
  ingressClassName: nginx
  rules:
    - host: shop.example.com          # CHANGE ME
      http:
        paths:
          - { path: /, pathType: Prefix, backend: { service: { name: frontend, port: { name: http } } } }
